import subprocess

# Compile the C code
subprocess.run(["gcc", "main.c", "-o", "main"])

# Run the compiled C program to generate points.dat
subprocess.run(["./main"])

print("points.dat generated by C program.")

